# Generated by Django 5.0.6 on 2024-08-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_brandname', models.CharField(max_length=255)),
                ('product_country', models.CharField(max_length=255)),
                ('product_number', models.PositiveIntegerField()),
                ('product_type', models.CharField(max_length=255)),
                ('product_stock', models.PositiveIntegerField()),
                ('product_view', models.CharField(max_length=255)),
                ('product_width', models.CharField(max_length=255)),
                ('product_diameter', models.CharField(max_length=255)),
                ('product_layer', models.PositiveIntegerField()),
                ('product_weight', models.PositiveIntegerField()),
                ('product_speed', models.PositiveIntegerField()),
                ('product_car_type', models.CharField(max_length=255)),
                ('product_model', models.CharField(max_length=255)),
                ('product_garanty_year', models.PositiveIntegerField()),
                ('product_create_year', models.PositiveIntegerField()),
                ('product_discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_price_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_discountpercent_this', models.PositiveIntegerField()),
                ('product_discountpercent_total', models.PositiveIntegerField()),
                ('product_profitpercent', models.PositiveIntegerField()),
                ('product_image', models.ImageField(upload_to='temporary_products/')),
            ],
        ),
    ]
