# Generated by Django 5.0.6 on 2024-08-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0002_temporaryproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryproduct',
            name='product_country',
        ),
        migrations.RemoveField(
            model_name='temporaryproduct',
            name='product_diameter',
        ),
        migrations.AddField(
            model_name='temporaryproduct',
            name='product_contry',
            field=models.CharField(default='ایران', max_length=100),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_brandname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_car_type',
            field=models.CharField(default='پژو', max_length=100),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_create_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_discount_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_discountpercent_this',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_discountpercent_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_garanty_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_layer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_model',
            field=models.CharField(default='206', max_length=100),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_price_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_profitpercent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_type',
            field=models.CharField(default='سواری', max_length=100),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temporaryproduct',
            name='product_Diameter',
            field=models.FloatField(default=0),
        ),
    ]
