# Generated by Django 5.0.6 on 2024-08-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0003_remove_temporaryproduct_product_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryproduct',
            name='seller_name',
            field=models.CharField(default='مدیر اصلی', max_length=255),
        ),
    ]
