# Generated by Django 5.0.6 on 2024-08-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0004_temporaryproduct_seller_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryproduct',
            name='seller_name',
        ),
    ]
