# Generated by Django 5.0.6 on 2024-07-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='product_name',
            new_name='name',
        ),
    ]
