# Generated by Django 5.0.6 on 2024-05-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_message', models.CharField(max_length=1000)),
                ('article_author', models.CharField(max_length=200)),
                ('article', models.IntegerField(default=0)),
                ('article_date', models.DateField()),
                ('article_image', models.ImageField(blank=True, upload_to='article/')),
            ],
        ),
    ]
