# Generated by Django 5.0.6 on 2024-07-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article',
        ),
    ]
