# Generated by Django 5.0.6 on 2024-05-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafishome', '0002_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_Diameter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='سواری', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(default=0),
        ),
    ]
