# Generated by Django 5.0.6 on 2024-05-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafishome', '0003_product_product_diameter_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brandname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_contry',
            field=models.CharField(default='ایران', max_length=100),
        ),
    ]
