# Generated by Django 5.0.6 on 2024-06-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafishome', '0004_product_product_brandname_product_product_contry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_layer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.IntegerField(default=0),
        ),
    ]
