# Generated by Django 5.0.6 on 2024-06-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafishome', '0005_product_product_layer_product_product_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discountpercent_this',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_discountpercent_total',
            field=models.IntegerField(default=0),
        ),
    ]
