# Generated by Django 5.0.6 on 2024-06-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafishome', '0006_product_product_discountpercent_this_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount_price',
            field=models.IntegerField(default=0),
        ),
    ]
