# Generated by Django 5.0.6 on 2024-06-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafishome', '0007_product_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_profitpercent',
            field=models.IntegerField(default=0),
        ),
    ]
