# Generated by Django 5.0.6 on 2024-07-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafishome', '0008_product_product_price_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_car_type',
            field=models.CharField(default='پژو', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_create_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_garanty_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.CharField(default='206', max_length=100),
        ),
    ]
