# Generated by Django 5.0.6 on 2024-07-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafishome', '0009_product_product_car_type_product_product_create_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_brandname',
            field=models.CharField(choices=[('ppp', 'انتخاب برند'), ('pegout', 'پژو'), ('tiba', 'تیبا'), ('l-90', 'ال نود')], default='ppp', max_length=50),
        ),
    ]
