# Generated by Django 5.0.6 on 2024-08-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafishome', '0013_review_optional_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('aspect_ratio', models.IntegerField()),
                ('diameter', models.IntegerField()),
            ],
        ),
    ]
