# Generated by Django 5.0.6 on 2024-08-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafishome', '0017_alter_product_product_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Diameter',
            field=models.FloatField(default=0),
        ),
    ]
