# Generated by Django 5.0.6 on 2024-08-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafishome', '0018_alter_product_product_diameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(default='مدیر اصلی', max_length=255),
        ),
    ]
